- name: In uppercase
  hosts: localhost
  tasks:
  - name: printing in uppercase
    vars:
      greeting: "hi hello"
    ansible.builtin.debug:
      msg: " in uppercase {{ greeting | upper }}"
  - name: printing in lowercase
    vars: 
      greeting: " HI HELLO"
    ansible.builtin.debug:
      msg: "in lowercase {{ greeting | lower }}"
  - name: duplicates
    vars:
      number: [1,3,4,5,6,7,6,1,1,4,4,44]
    ansible.builtin.debug: 
      msg: "remove duplicates  {{ number | unique }}"
  - name : minimum age
    vars:
      ages: [30,45,65,35,]
    ansible.builtin.debug:
      msg: "minimum age is {{ ages | min }}"
  - name: convert maps to list
    vars: 
      experience:
       devops: 3
       linux: 4
       terraform: 8
    ansible.builtin.debug:
      msg: "before convert {{experience}}"
  - name: after converting
    vars: 
      experience:
       devops: 3
       linux: 4
       terraform: 8
    ansible.builtin.debug:
       msg: "after converting{{ experience | dict2items }}"
  - name: convert item to dict
    vars:
      memory:
      - 8gb
      - 10gb
      - 64gb
    ansible.builtin.debug:
      msg: " convert into dictionary {{ memory | items2dict }}" 

   