- name: In uppercase
  hosts: localhost
  tasks:
  - name: printing in uppercase
    vars:
      greeting: "hi hello"
    ansible.builtin.debug:
      msg: " in uppercase {{ greeting | upper }}"
  - name: printing in lowercase
    vars: 
      greeting: " HI HELLO"
    ansible.builtin.debug:
      msg: "in lowercase {{ greeting | lower }}"
  - name: duplicates
    vars:
      number: [1,3,4,5,6,7,6,4]
    ansible.builtin.debug: 
      msg: "remove duplicates  {{ number | unique }}"