- name: In uppercase
  hosts: localhost
  tasks:
  - name: printing in uppercase
    vars:
      greeting: "hi hello"
    ansible.builtin.debug:
      msg: " in uppercase {{ greeting | upper }}"
  - name: printing in lowercase
    vars: 
      greeting: " HI HELLO"
    ansible.builtin.debug:
      msg: "in lowercase {{ greeting | lower }}"