- name: check the number
  hosts: localhost
  vars_prompt:
   - name: number
     prompt: please enter the number
     private: no
  tasks:
   - name: number is lessthe 10
     ansible.builtin.bebug:
       msg: "given number {{number}} is less than 10"
     when: number < 10
  tasks:
   - name: number is greater than 10
     ansible.builtin.bebug:
        msg: "given number is greater then 10"
     when: number > 10