- name: install nginx
  hosts: web
  become: yes
  tasks: 
  - name: install
    ansible.builtin.dnf:
      name: nginx
      state: present
  - name: printing the information
    ansible.builtin.debug:
      msg: "installed nginx" 