- name: installing packages
  hosts: db
  become: yes
  tasks:
  - name: installing in remote server
    ansible.builtin.dnf:
     name: "{{ item }}"
     state: latest
    loop:
    - mysql
    - nginx
    - postfix

