- name: installing packages
  hosts: db
  become: yes
  tasks:
  - name: installing in remote server
    ansible.builtin.dnf:
     name: "{{ item.name }}"
     state: "{{ item.state }}"
    loop:
    - { 'name' : 'mysql' , 'state' : 'present' }
    - { 'name' : 'nginx' , 'state' : 'absent' } 
    - { 'name' : 'postfix' , 'state' : 'absent'}
    

