- name: prefernces of variables
  hosts: localhost
  #vars:
   # wishes: "wishes from variables"
  vars_files:
  - vars.yaml

  tasks: 
  - name: variables from differnet places
    ansible.builtin.debug:
      msg: "hello,{{wishes}}"


#1.arguments at cmd level
#2.task level
#3.variables from files
#4. variables from prompt
#5. variables from play