- name: practicing ansible
  hosts: localhost
  vars:
    details:
      devops: 3
      linux: 4
      terraform: 5
    tasks:
    - name: pritning the information
      ansible.builtin.debug:
        msg_print: "{{details}}"
      vars:
        items:
        - shell script
        - anisible
        - putty
        - super putty
      ansible.builtin.debug:
        msg: "{{items}}"