- name: practicing ansible
  hosts: localhost
  
  tasks:
  - name: pritning the information
    vars:
     items:
     - shell script
     - anisible
     - putty
     - super putty
     details:
      devops: 3
      linux: 4
      terraform: 5
    ansible.builtin.debug:
       msg: "{{items}} and {{details}}"