- name: print th user information
  hosts: localhost
  tasks:
  - name: adding user
    anisible.builtin.command: id expense
     register: user
     ignore_errors: true
    ansible.builtin.debug:
      msg: "{{user}}"
  
