- name: print the user information
  hosts: localhost
  tasks:
  - name: adding user
    ansible.builtin.command: id ramesh
    register: user
    ignore_errors: true
  - name: print the information
    ansible.builtin.debug:
      msg: "{{user}}"
  - name: adding user
    ansible.builtin.command: useradd ramesh
  # register: user
    when: user.rc != 0
  - name: printing the information
    ansible.builtin.debug:
      msg: "hello user added"

  
  
