- name: print the user information
  hosts: localhost
  tasks:
  - name: adding user
    ansible.builtin.command: id expense
    register: user
    ignore_errors: true
  - name: print the information
    ansible.builtin.debug:
      msg: "{{user}}"
  - name: adding user
    ansible.builtin.command: useradd expense
    register: user
  - name: printing the information
    ansible.builtin.debug:
      msg:{{user}}

  
  
