- name: practicing ansible
  hosts: localhost
  
  tasks:
  - name: pritning the information
    vars:
      items:
      - shell script
      - anisible
      - putty
      - super putty
    ansible.builtin.debug:
      msg: "{{items}}"
    vars:
     details:
      devops: 3
      linux: 4
      terraform: 5
    ansible.builtin.debug:
       msg: "{{details}}"