- name: variables from files
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks: 
  - name: print information
    ansible.builtin.debug:
      msg: "hi iam learing {{course}} from trainer {{trainer}} with duration of {{duration}}"
