- name: variables from prompt
  hosts: localhost
  var_prompt:
  - name: USERNAME
    prompt: "please enter username"
    private: flase
  - name: PASSWORD
    prompt: "please enter password"
    private: true
  tasks:
  - name: accessing variables from prompt
    ansible.builtin.debug:
      msg: "hi,username:{{USERNAME}},password:{{PASSWORD}}"

