- name: variables from inventory
  hosts: localhost
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "hi,learing {{course}}, from trainer {{trainer}} and duration is {{duration}}"
